// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/hanariu/hanariu/pkg/hanariu"

import atoms "github.com/hanariu/hanariu/pkg/hanariu/atoms"
import protons "github.com/hanariu/hanariu/pkg/hanariu/protons"

type RatingBosons struct {
	Description      string `default:""`
	DescriptionTag   string `default:"span"`
	DescriptionStyle string `default:"secondary"`
	DescriptionSize  string `default:"md"`
	BackgroundColor  string `default:"current"`
	Value            float64
	IconOptions      protons.IconFillBosons
}

var descriptionStyles = hanariu.Boson{
	"primary":   "text-primary-800 dark:text-primary-200",
	"secondary": "text-secondary-800 dark:text-secondary-200",
	"warning":   "text-warning-800 dark:text-warning-200",
	"danger":    "text-danger-800 dark:text-danger-200",
	"success":   "text-success-800 dark:text-success-200",
	"info":      "text-info-800 dark:text-info-200",
}

var DescriptionSizes = hanariu.Boson{
	"xs": "text-xs",
	"sm": "text-sm",
	"md": "text-base",
	"lg": "text-lg",
	"xl": "text-xl",
}

func RatingDescription(props *RatingBosons) templ.Component {
	descriptionStyle := hanariu.GetTagDefault("DescriptionStyle", props.DescriptionStyle, RatingBosons{})
	descriptionSize := hanariu.GetTagDefault("DescriptionSize", props.DescriptionSize, RatingBosons{})
	return hanariu.CreateComponent(hanariu.GetTagDefault("DescriptionTag", props.DescriptionTag, RatingBosons{}), descriptionStyles[descriptionStyle]+" "+DescriptionSizes[descriptionSize], nil, false)
}

func Rating(props *RatingBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><div class=\"flex\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i := range 5 {
			templ_7745c5c3_Err = atoms.RatingStar(&atoms.RatingStarBosons{Fill: props.Value - float64(i), IconOptions: props.IconOptions, BackgroundColor: hanariu.GetTagDefault("BackgroundColor", props.BackgroundColor, RatingBosons{})}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Description != "" {
			templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Description)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/molecules/rating.templ`, Line: 50, Col: 23}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = RatingDescription(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
