// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	hanariu "github.com/hanariu/hanariu/pkg/hanariu"
)

type IconFillBosons struct {
	Size      string `default:"md"`
	Color     string `default:"gold"`
	ViewBox   string `default:"0 0 32 32"`
	Direction string `default:"right"`
	Fill      float64
	NoClass   bool
	Attrs     hanariu.Attrs
}

var iconFillDisplayStyles = hanariu.Boson{
	"gold":      "fill-yellow-400",
	"current":   "fill-current",
	"primary":   "fill-primary-600 dark:fill-primary-300",
	"secondary": "fill-secondary-600 dark:fill-secondary-300",
	"warning":   "fill-warning-600 dark:fill-warning-300",
	"danger":    "fill-danger-600 dark:fill-danger-300",
	"success":   "fill-success-600 dark:fill-success-300",
	"info":      "fill-info-600 dark:fill-info-300",
}

var iconFillSizeStyles = hanariu.Boson{
	"full": "w-full h-full",
	"xs":   "w-4 h-4",
	"sm":   "w-6 h-6",
	"md":   "w-8 h-8",
	"lg":   "w-10 h-10",
	"xl":   "w-12 h-12",
}

func (attr *IconFillBosons) makeIconFillAttrs() {
	attrs := make(hanariu.Attrs)
	for k, v := range attr.Attrs {
		attrs[k] = v
	}
	attr.Attrs = attrs
}

func (prop *IconFillBosons) addIconFillAttr(k, v string) {
	prop.Attrs[k] = v
}

func IconFill(props *IconFillBosons) templ.Component {
	var classes = ""
	if !props.NoClass {
		classes += getIconFillClasses(props.Size, props.Color)
	}
	props.makeIconFillAttrs()
	props.addIconFillAttr("style", getFillMask(props))
	props.addIconFillAttr("viewbox", hanariu.GetTagDefault("ViewBox", props.ViewBox, IconFillBosons{}))
	props.addIconFillAttr("viewbox", hanariu.GetTagDefault("ViewBox", props.ViewBox, IconFillBosons{}))
	return hanariu.CreateComponent("svg", classes, props.Attrs, false)
}

func getIconFillClasses(size, color string) string {
	sizeIcon := hanariu.GetTagDefault("Size", size, IconFillBosons{})
	colorIcon := hanariu.GetTagDefault("Color", color, IconFillBosons{})
	return iconFillDisplayStyles[colorIcon] + " " + iconFillSizeStyles[sizeIcon]
}

func getFillMask(props *IconFillBosons) string {
	percent := int(max(min(props.Fill, 1), 0) * 100)
	direction := hanariu.GetTagDefault("Direction", props.Direction, IconFillBosons{})
	return fmt.Sprintf(
		"mask-image: linear-gradient(to %s, black %d%%, transparent %d%%); mask-repeat: no-repeat; mask-size: 100%% 100%%;", direction, percent, percent)
}

var _ = templruntime.GeneratedTemplate
