// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	hanariu "github.com/hanariu/hanariu/pkg/hanariu"
)

type SpinnerBosons struct {
	Size  string `default:"md"`
	Color string `default:"primary"`
}

var spinnerSizeStyles = hanariu.Boson{
	"xs": "h-4 w-4 border-[2px]",
	"sm": "h-6 w-6 border-[3px]",
	"md": "h-8 w-8 border-[4px]",
	"lg": "h-12 w-12 border-[5px]",
	"xl": "h-16 w-16 border-[6px]",
}

var spinnerColorStyles = hanariu.Boson{
	"primary":   "border-primary-600 dark:border-primary-400",
	"secondary": "border-secondary-600 dark:border-secondary-400",
	"warning":   "border-warning-600 dark:border-warning-400",
	"danger":    "border-danger-600 dark:border-danger-400",
	"success":   "border-success-600 dark:border-success-400",
	"info":      "border-info-600 dark:border-info-400",
}

var spinnerStyles = hanariu.Boson{
	"spinner": "animate-spin border-b-transparent dark:border-b-transparent rounded-[50%] inline-block box-border border-solid",
}

func Spinner(props *SpinnerBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{getSpinnerClasses(props.Size, props.Color)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/protons/spinner.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"w-12\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getSpinnerClasses(size, color string) string {
	spinnerColor := hanariu.GetTagDefault("Color", color, SpinnerBosons{})
	spinnerSize := hanariu.GetTagDefault("Size", size, SpinnerBosons{})
	return hanariu.CreateClasses("Size", spinnerSize, SpinnerBosons{}, spinnerSizeStyles) + " " + hanariu.CreateClasses("Color", spinnerColor, SpinnerBosons{}, spinnerColorStyles) + " " + spinnerStyles["spinner"]
}

var _ = templruntime.GeneratedTemplate
