// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/hanariu/hanariu/pkg/hanariu"
	protons "github.com/hanariu/hanariu/pkg/hanariu/protons"
)

type ButtonLinkBosons struct {
	Size     string `default:"md"`
	Color    string `default:"primary"`
	Type     string `default:"button"`
	Tag      string `default:"button"`
	Disabled bool
	Full     bool
	Reverse  bool
	Title    string
	Attrs    hanariu.Attrs
}

var buttonLinkStyles = hanariu.Boson{
	"default": "relative inline-flex items-center justify-center font-semibold rounded-sm",
	"active":  "transition duration-150 ease-in-out text-opacity-95 hover:text-opacity-100",
	"reverse": "flex-row-reverse",
	"full":    "w-full",
}

var buttonLinkColorStyles = hanariu.Boson{
	"primary":   "text-primary-700 hover:text-primary-800 dark:text-primary-200 dark:hover:text-primary-50",
	"secondary": "text-secondary-700 hover:text-secondary-800 dark:text-secondary-200 dark:hover:text-secondary-50",
	"warning":   "text-warning-700 hover:text-warning-800 dark:text-warning-200 dark:hover:text-warning-50",
	"danger":    "text-danger-700 hover:text-danger-800 dark:text-danger-200 dark:hover:text-danger-50",
	"success":   "text-success-700 hover:text-success-800 dark:text-success-200 dark:hover:text-success-50",
	"info":      "text-info-700 hover:text-info-800 dark:text-info-200 dark:hover:text-info-50",
}

var buttonLinkColorDisabledStyles = hanariu.Boson{
	"primary":   "text-primary-700/50 dark:text-primary-500/50",
	"secondary": "text-secondary-700/50 dark:text-secondary-500/50",
	"warning":   "text-warning-700/50 dark:text-warning-500/50",
	"danger":    "text-danger-700/50 dark:text-danger-500/50",
	"success":   "text-success-700/50 dark:text-success-500/50",
	"info":      "text-info-700/50 dark:text-infor-500/50",
}

var buttonLinkSizeStyles = hanariu.Boson{
	"xs": "text-xs",
	"sm": "text-sm",
	"md": "text-base",
	"lg": "text-lg",
	"xl": "text-xl",
}

func ButtonLink(props *ButtonLinkBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/atoms/buttonLink.templ`, Line: 55, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = getButtonLink(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ButtonLinkIcon(props *ButtonLinkBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templ_7745c5c3_Var4.Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = protons.IconButton(&protons.IconButtonBosons{Size: props.Size, Reverse: props.Reverse}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/atoms/buttonLink.templ`, Line: 64, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = getButtonLink(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func (attr *ButtonLinkBosons) makeButtonLinkAttrs() {
	attrs := make(hanariu.Attrs)
	for k, v := range attr.Attrs {
		attrs[k] = v
	}
	attr.Attrs = attrs
}

func (prop *ButtonLinkBosons) addButtonLinkAttr(k, v string) {
	prop.Attrs[k] = v
}

func getButtonLink(props *ButtonLinkBosons) templ.Component {
	props.Size = hanariu.GetTagDefault("Size", props.Size, ButtonBosons{})
	props.Color = hanariu.GetTagDefault("Color", props.Color, ButtonBosons{})
	props.Type = hanariu.GetTagDefault("Type", props.Type, ButtonBosons{})
	props.makeButtonLinkAttrs()
	props.addButtonLinkAttr("type", props.Type)
	props.Tag = hanariu.GetTagDefault("Tag", props.Tag, ButtonBosons{})
	if props.Disabled && props.Type == "button" {
		props.addButtonLinkAttr("disabled", "")
	}
	classes := getButtonLinkClasses(props)
	return hanariu.CreateComponent(props.Tag, classes, props.Attrs, false)
}

func getButtonLinkClasses(props *ButtonLinkBosons) string {
	var classes = buttonLinkStyles["default"] + " " + buttonLinkSizeStyles[props.Size]

	if props.Reverse {
		classes += " " + buttonLinkStyles["reverse"]
	}

	if props.Disabled {
		classes += " " + buttonLinkColorDisabledStyles[props.Color]
	} else {
		classes += " " + buttonLinkStyles["active"] + " " + buttonLinkColorStyles[props.Color]
	}

	if props.Full {
		classes += " " + buttonLinkStyles["full"]
	}

	return classes
}

var _ = templruntime.GeneratedTemplate
