// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/hanariu/hanariu/pkg/hanariu"
)

type DropdownBosons struct {
	Id        string `default:"dropdown"`
	Placement string `default:"bottom"`
	Offset    string `default:"10"`
}

func Dropdown(props *DropdownBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"border-0 bg-white dark:bg-primary-900 rounded-md z-30\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div data-arrow=\"arrow\" class=\"absolute h-2 w-2 rotate-45 bg-white border-secondary-200/75 dark:bg-primary-900 dark:border-primary-950/40\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = dropdownContent(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func dropdownContent(props *DropdownBosons) templ.Component {
	attrs := make(hanariu.Attrs)

	var bind = "{['data-x-transition:enter']: 'transition transform-cpu ease-out duration-100',['data-x-transition:enter-start']: 'transition transform-cpu opacity-0 scale-95',['data-x-transition:enter-end']: 'transition transform-cpu opacity-100 scale-100',['data-x-transition:leave']: 'transition transform-cpu ease-in duration-75',['data-x-transition:leave-start']: 'transition transform-cpu opacity-100 scale-100',['data-x-transition:leave-end']: 'transition transform-cpu opacity-0 scale-95'"
	bind += ", ['data-x-on:click.outside']() { open = false }"
	bind += "}"
	attrs["data-x-cloak"] = ""
	attrs["data-x-show"] = "open"
	idProp := hanariu.GetTagDefault("Id", props.Id, DropdownBosons{})
	placementProp := hanariu.GetTagDefault("Placement", props.Placement, DropdownBosons{})
	offsetProp := hanariu.GetTagDefault("Offset", props.Offset, DropdownBosons{})

	var anchor = "data-x-anchor." + placementProp + ".offset." + offsetProp
	attrs[anchor] = "$refs." + idProp
	attrs["data-x-bind"] = bind

	class := "absolute z-40 border rounded-md shadow-md w-max bg-white border-secondary-200/75 dark:bg-primary-900 dark:border-primary-950/40"

	return hanariu.CreateComponent("div", class, attrs, false)
}

var _ = templruntime.GeneratedTemplate
